= smf

image:https://travis-ci.org/jiro4989/smf.svg?branch=master["Build Status", link="https://travis-ci.org/jiro4989/smf"]

smf is a library for SMF (Standard MIDI File).

== SMFのデータ書式について

SMFのデータ構造として最初に**ヘッダチャンク**と**トラックチャンク**の2つに大分できる。
ヘッダチャンクはSMFに必ず1つ存在し、トラックチャンクはSFMに必ず**1つ以上**する。

以降にヘッダチャンクとトラックチャンクのデータ書式についてを記載する。

=== ヘッダチャンク

ヘッダチャンクは以下のようなデータを持つ。
ヘッダチャンクの要素はすべて固定長のデータであるため、
ヘッダチャンク全体のデータ長は常に14byteである。

[options="header"]
|----------------------------
|分類           |バイトサイズ
|チャンクタイプ |4byte
|データ長       |4byte
|フォーマット   |2byte
|トラック数     |2byte
|時間単位       |2byte
|----------------------------

==== チャンクタイプ

チャンクタイプの値は常に固定である。
バイトデータで `[0x4d, 0x54, 0x68, 0x64]` である。
これは文字列に変換した際に"MThd"になる。

[source,nim]
----
from sequtils import mapIt

doAssert [0x4d, 0x54, 0x68, 0x64].mapIt(it.char) == @['M', 'T', 'h', 'd']
----

==== データ長

ヘッダチャンクの残りのデータの長さである。
ヘッダチャンクは固定長のデータしか持たないため、
データ長の値は常に `[0, 0, 0, 6]` である。

==== フォーマット

SMFのフォーマット種類である。
SMFにはFORMAT0〜2まである。
FORMAT1の場合は `[0, 1]` になる。

===== FORMAT0

トラックチャンクを１つしか持たないフォーマット。
１つのトラックチャンクにすべての楽器データが含まれる。

===== FORMAT1

1つのトラックチャンクに楽器の種類が1つであるフォーマット。
楽器を2つ使用して演奏するSMFファイルの場合はトラックチャンクにの数は2つになる。

===== FORMAT2

ボクも知らないし、実装していない。

==== トラック数

トラックチャンクにいくつトラックが存在するかを指定する。
FORMAT0の場合はトラックが1つだけであるため、 `[0, 1]` に自動的に決まる。
FORMAT1の場合は、トラックの数が変動するため、この値も変動する。

==== 時間単位

分解能
TODO

=== トラックチャンク

TODO

== Usage

[source,nim]
----
import smf

var s = newSMF()

var midiEvent1 = newMIDIEvent(0, statusOn)
s.add midiEvent1

writeFile("a.smf", s)
----

[quote]
____
00000000: 4d54 6864 0000 0006 0001 0002 0180 4d54  MThd..........MT
00000010: 726b 0000 0048 00f0 057e 7f09 01f7 00ff  rk...H...~......
00000020: 2101 0000 ff09 134d 6964 6920 5468 726f  !......Midi Thro
00000030: 7567 6820 506f 7274 2d30 00ff 0307 5472  ugh Port-0....Tr
00000040: 6163 6b20 3100 ff04 0247 4d00 ff51 0307  ack 1....GM..Q..
00000050: a120 00ff 5804 0402 1808 00ff 2f00 4d54  . ..X......./.MT
00000060: 726b 0000 002b 00ff 2101 0000 ff09 134d  rk...+..!......M
00000070: 6964 6920 5468 726f 7567 6820 506f 7274  idi Through Port
00000080: 2d30 00ff 0307 5472 6163 6b20 3200 ff2f  -0....Track 2../
00000090: 00                                       .
____

== Document

* https://jiro4989.github.io/smf/smf.html
* https://sites.google.com/site/yyagisite/material/smfspec